Cleaner text - I hope
NicoKos/resume_connection pull request #76
Opened 2023-05-09 17:29 UTC by gorryfair

This attempts to align the two halves of the document, with sections both aligned to the phases defined.

2023-05-09 18:26 UTC, gorryfair commented
Please review and commit ... G

2023-05-10 12:32 UTC, NicoKos requested changes

2023-05-10 12:32 UTC, NicoKos commented on draft-kuhn-tsvwg-careful-resume-01.xml
> -<rfc category="info" docName="draft-kuhn-tsvwg-careful-resume-01"
Should we version 01 and not 02.

2023-05-10 12:34 UTC, NicoKos approved these changes

2023-05-10 12:34 UTC, merged